#!/bin/sh
set -e

case "$1" in
    install|configure)
        ajcfg="/etc/ajenti/config.yml"
        webuietc="/usr/lib/linuxmuster-webui/etc"
     if [ ! -f $webuietc/.installed ];
      then
        # do first install
        pip install -U pip wheel setuptools distribute
        hash -r
        pip install -r $webuietc/requirements.txt
        #echo "link ajcfg to linuxmuster-webui folder"
        #ln -s $ajcfg $webuietc
        #rm /etc/ajenti/config.yml
        cp /usr/lib/linuxmuster-webui/etc/ajenti_default.yml /etc/ajenti/config.yml
        # Set default permissions from true to false
        echo "set reverse permissions"
        sed -i "s/: True,/: False,/g" /usr/local/lib/python2.7/dist-packages/ajenti_plugin_core/main.py
        # Delete sensitive config items in default template
        # TODO: Fix this
        #echo "Delete linumuster special config items"
        #sed -i 's/json\.dumps(aj\.config\.data)/json\.dumps(config_angular)/' /usr/local/lib/python2.7/dist-packages/ajenti_plugin_core/views/main.py
        #sed -i '/from aj\.api\.endpoint/a# Del sensitive config items\nconfig_angular = aj.config.data\ndel config_angular["linuxmuster"]' /usr/local/lib/python2.7/dist-packages/ajenti_plugin_core/views/main.py
        # systemctl einrichten und starten
        echo "configure systemctl.."
        systemctl daemon-reload
        systemctl enable linuxmuster-webui
        systemctl start linuxmuster-webui
        touch $webuietc/.installed
        touch /etc/linuxmuster/sophomorix/default-school/students.csv
        touch /etc/linuxmuster/sophomorix/default-school/teachers.csv
        touch /etc/linuxmuster/sophomorix/default-school/extrastudents.csv
        touch /etc/linuxmuster/sophomorix/default-school/extraclasses.csv
        hostname=$(hostname --fqdn)
        ipaddress=$(hostname --ip-address)
        echo "---------------------------------------------------------------"
        echo "linuxmuster-webui is now installed but not initialised!  http://$ipaddress:8000"
        echo "---------------------------------------------------------------"
     else
    # do update
    echo "---------------------------------------------------------------"
        echo "updating linuxmuster-webui"
        echo "---------------------------------------------------------------"
    echo "Stop linuxmuster-webui"
#    sed -i -e  's/dialog ng:show="message.visible" ng:repeat="message in messagebox.messages"/dialog ng:show="message.visible" style="z-index: 1050" ng:repeat="message in messagebox.messages"/' /usr/local/lib/python2.7/dist-packages/ajenti_plugin_core/resources/js/core/directives/messageboxContainer.es
#    rm -rf /usr/local/lib/python2.7/dist-packages/ajenti_plugin_core/resources/build/
#    cp -R /usr/lib/linuxmuster-webui/etc/core-build/* /usr/local/lib/python2.7/dist-packages/ajenti_plugin_core/resources/build/
    systemctl stop linuxmuster-webui
    pip install -r $webuietc/requirements.txt -q
    # Set default permissions from true to false
    echo "set reverse permissions"
    sed -i "s/: True,/: False,/g" /usr/local/lib/python2.7/dist-packages/ajenti_plugin_core/main.py
    echo "set default sophomorix webui rights"
    /usr/sbin/sophomorix-ui
    # start webui
    echo "Start linuxmuster-webui"
    systemctl start linuxmuster-webui
        echo "---------------------------------------------------------------"
        echo "updating linuxmuster-webui ..done"
        echo "---------------------------------------------------------------"
     fi
        ;;
    upgrade|abort-upgrade)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0
