#!/bin/sh
set -e

case "$1" in
    install|configure)
        ajcfg="/etc/ajenti/config.yml"
        webuietc="/usr/lib/linuxmuster-webui/etc"
     if [ ! -f $webuietc/.installed ];
      then
	# do first install
	pip install -U pip wheel setuptools distribute
	hash -r
	pip install -r $webuietc/requirements.txt
	echo "link ajcfg to linuxmuster-webui folder"
	ln -s $ajcfg $webuietc
	# Set default permissions from true to false
	echo "set reverse permissions"
	sed -i "s/: True,/: False,/g" /usr/local/lib/python2.7/dist-packages/ajenti_plugin_core/main.py
	# systemctl einrichten und starten
	echo "configure systemctl.."
	systemctl daemon-reload
	systemctl enable linuxmuster-webui
	systemctl start linuxmuster-webui
	touch $webuietc/.installed
	hostname=$(hostname --fqdn)
	echo "---------------------------------------------------------------"
	echo "linuxmuster-webui is now installed but not initialised!  https://$hostname:8000"
	echo "---------------------------------------------------------------"
     else
	# do update
	echo "---------------------------------------------------------------"
        echo "updating linuxmuster-webui"
        echo "---------------------------------------------------------------"
	echo "Stop linuxmuster-webui"
	systemctl stop linuxmuster-webui
	pip install -r $webuietc/requirements.txt -q
	# Set default permissions from true to false
	echo "set reverse permissions"
	sed -i "s/: True,/: False,/g" /usr/local/lib/python2.7/dist-packages/ajenti_plugin_core/main.py
	# start webui
	echo "Start linuxmuster-webui"
	systemctl start linuxmuster-webui
        echo "---------------------------------------------------------------"
        echo "updating linuxmuster-webui ..done"
        echo "---------------------------------------------------------------"
     fi
        ;;
    upgrade|abort-upgrade)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0
